### ISSUE TITLE
lessons

### ISSUE THREAD

**Issue by zokratez** [learn-co-curriculum/ttt-7-valid-move#13]
im just emailing to find out if my lessons are in order. I was prompted to do so by one of your employees as my lessons seem to be ok with me but maybe they were move from the chronologically order 

seema said a minute ago
ok

seema said just now
yeah maybe use the raise an issue feature and report this

seema said just now
because they may be in the wrong order now

sam said just now

**Comment by PeterBell** [comment]
Hey @zokratez thanks so much for sharing. Could you check the order @AnnJohn ? LMK if I can do anything to help!
