### ISSUE TITLE
needs review

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/ttt-7-valid-move#2]
this will close #1 

here is git diff from my commits: https://github.com/learn-co-curriculum/ttt-7-valid-move/commit/29b3f8abc90bbcef1631c91a136745b8891f5dcc

@aviflombaum

**Comment by AnnJohn** [comment]
@aviflombaum setting a deadline for today 9/11/15

**Comment by aviflombaum** [comment]
Done, very minor edits, great job @SophieDeBenedetto https://github.com/learn-co-curriculum/ttt-7-valid-move/commit/647b688760b565d1460483ae3ac5aa716f6a40c4
