### ISSUE TITLE
Bolded "do"

### ISSUE THREAD

**Issue by margaretzhu** [learn-co-curriculum/ttt-7-valid-move#21]
Hi Learn.co curriculum owners, 

In this lesson, there is an example of how a method can be used directly in a conditional expression. The bolded "do" in the example threw me off -- Although I have seen "do" in spec/rspec code before, I have never seen it used in methods. So when I tried writing code for my method with "do", it failed several times. I reached out to Learn.co community members through Ask a Question for help with my method (and questions about "do"), and they told me that it was a typo: the "do" in "do some stuff" and "do some other stuff" should not be bolded; "do" is simply part of the sentence. 

Simply unbolding "do" would  greatly clarify the example! Attached is a screenshot of the example code I am referring to. 

Happily Learning :), 
Margaret

<img width="1017" alt="issue with valid tic tac toe move" src="https://cloud.githubusercontent.com/assets/19864837/16285720/addb5e0c-388c-11e6-92ec-86d54b507b85.png">

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
