### ISSUE TITLE
Tic Tac Toe Valid Move lab

### ISSUE THREAD

**Issue by kbarroso** [learn-co-curriculum/ttt-7-valid-move#23]
Hello all, 

Issue: The Readme of this lab mentions that you have to account for a user's input of 1-9 when they select a space on the Tic Tac Toe board and convert that number to an array's index number system of 0-8. 

From Readme:
**"Arrays are indexed starting at 0 and a user playing your game is unlikely to know that. When a user types in that they'd like to fill position 1, they really mean that they'd like to fill the board array at the index of 0. You'll have to account for this in your method."**

There are 3 errors you have to clear to pass this lab and all of the test use an index number to check if your code meets the expectations of the test. 

Test expectations: 
  it 'returns true for a valid position on an empty board' do
    board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
    index = 0
    expect(valid_move?(board, index)).to be_truthy
  end

  it 'returns nil or false for an occupied position' do
    board = [" ", " ", " ", " ", "X", " ", " ", " ", " "]
    index = 4

```
expect(valid_move?(board, index)).to be_falsey
```

  end

  it 'returns nil or false for a position that is not on the board' do
    board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
    index = 100

```
expect(valid_move?(board, index)).to be_falsey
```

  end

end

Recommendation: 
I humbly recommend to remove the section pasted above from the Readme.

**Comment by gj** [comment]
Fixed in 3cb45be. Thanks @kbarroso !

**Comment by kbarroso** [comment]
Your welcome, Gabe. Have a great day!

**Comment by gj** [comment]
Back at you 🙂
