### ISSUE TITLE
Index vs. Index-1

### ISSUE THREAD

**Issue by anglinchristina** [learn-co-curriculum/ttt-7-valid-move#24]
The lab specifies that the user input will be 1-9, suggesting that we need to subtract 1 from the index param that's passed to valid_move?.  But in the rspec file, the user input is the actual index (first test case has index == 0).

**Comment by ghost** [comment]
This is what I came to report. It's good in that it forces the student to check the test, but it goes against what the lab's text says you will need to do.

**Comment by gj** [comment]
Fixed in 3cb45be. Thanks @anglinchristina !
