### ISSUE TITLE
Wrong code passed tests

### ISSUE THREAD

**Issue by timothyhart6** [learn-co-curriculum/ttt-7-valid-move#25]
Hello!

When I first started this lab (ttt-7-valid-move) I was able to pass it with the following method:

def valid_move? (board, index)
  board[index] == " "
end

The lab requires using #position_taken? as a helper method so I figured that was not the proper way to complete it, and was able to pass it the right way with different code.  Not sure if it actually matters, but I figured I would just bring it to your attention.  Thanks!

-Tim

**Comment by gj** [comment]
Fixed in 3cb45be. Thanks @timothyhart6 !
