### ISSUE TITLE
Telling Learn student to account for user choice to correct index conversion

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/ttt-7-valid-move#27]
The instructions tell the Learn student to compensate for a user selecting between 1–9 positions on the Tic Tac Toe board, but really meaning 0-8 indexes of the board array. However, the first test passes in 0 as the index parameter value and expects "truthy"; which is confusing because, if the student has done something like (board_index = index - 1), this test will not pass because -1 isn't a valid index. 

The first test should really pass in "1" so the student can convert that to index "0", like the instructions say to do.
<img width="528" alt="screen shot 2017-04-12 at 8 46 25 am" src="https://cloud.githubusercontent.com/assets/21230656/24958207/8fc49368-1f5c-11e7-85e3-22e3e1980a03.png">
<img width="864" alt="screen shot 2017-04-12 at 8 46 55 am" src="https://cloud.githubusercontent.com/assets/21230656/24958226/a1d8aaf8-1f5c-11e7-8898-69e9befc84b2.png">

**Comment by gj** [comment]
Fixed in 3cb45be. Thanks @kyleblee !
