### ISSUE TITLE
confusing instruction...

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/ttt-7-valid-move#29]
Why is the following instruction in this lab?

"Arrays are indexed starting at 0 and a user playing your game is unlikely to know that. When a user types in that they'd like to fill position 1, they really mean that they'd like to fill the board array at the index of 0. You'll have to account for this in your method."

It's confusing...

You're already telling me in the next instruction:

"The valid positions on the board, from the user's point of view, are 1-9, but we'll be checking to see if we have a number between 0-8 because we'll be looking at the array index. If the user inputs a number not included in that range, their input is invalid. There are a few different ways to check to see if a number is included in a range. Look up the #between? method for starters."

Just feedback

**Comment by kwebster2** [comment]
@aturkewi @cjbrock 
I had another student who was also confused by this instruction. The second bullet point already describes the relevant discrepancy between a user's input and the corresponding index, so the first adds some confusion as to whether or not `1` will need to be subtracted from the index that is passed in. It may help to just remove the first bullet point altogether.

**Comment by yinazee** [comment]
yes, i was also confused by this bullet:

Arrays are indexed starting at 0 and a user playing your game is unlikely to know that. When a user types in that they'd like to fill position 1, they really mean that they'd like to fill the board array at the index of 0. You'll have to account for this in your method.

but with the help of @kwebster2, he helped clarify to me that I actually dont need it in my method.

**Comment by gj** [comment]
Fixed in 3cb45be. Thanks @Ary770 !
