### ISSUE TITLE
postion_taken? does not require "" and nil to pass

### ISSUE THREAD

**Issue by cthulhu-uu** [learn-co-curriculum/ttt-7-valid-move#32]
The previous lesson requires position_taken? to read "" and nil as false, whereas this lesson does not test for this requirement. The below code has that requirement commented out and passes the test.

```rb
def valid_move?(board, pos)
 return true while pos < 9 && position_taken?(board, pos) == false
 return false
end

def position_taken?(board, pos)
  if board[pos] == " " #|| board[pos] == "" || board[pos] == nil
    return false
  end
  return true
end
```

As this lesson builds on the previous one, it is expected to have the same requirements and should not pass without it. Changing the requirements can cause confusion.

**Comment by cjbrock** [comment]
Hey @cthulhu-uu! You're correct that the lessons do build on one another, however while you can re-use some of the same code as a developer, part of becoming a developer is realizing that the process is iterative and you're definitely going to have to refactor your code now and then, which is intentionally built in to the curriculum. 
// <3 Corinna
