### ISSUE TITLE
maybe I did this wrong, but I had to alter my position_taken? method for this lab

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/ttt-7-valid-move#6]
in the lab where `position_taken?` was originally defined, the positions were being passed in as indices..but in this lab, they are passed in as if they are user input.

(maybe i did the previous lab wrong?)

**Comment by mendelB** [comment]
@loganhasson I believe the `position_taken?` method is indeed using indices, but the `valid_move?` method being tested is meant to be dealing with user input (and converting that appropriately when calling `position_taken?`).
