### ISSUE TITLE
First two position variables are strings should be ints

### ISSUE THREAD

**Issue by DavidGrey** [learn-co-curriculum/ttt-7-valid-move#7]
From valid_move_spec.rb

```
7. board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
8. position = "1" #<<<Should be int
9. expect(valid_move?(board, position)).to be_truthy


13. board = [" ", " ", " ", " ", "X", " ", " ", " ", " "]
14. position = "5"#<<<Should be int

16. expect(valid_move?(board, position)).to be_falsey
```

The last position variable(line 21) is an int. The other two should match.

**Comment by mendelB** [comment]
@DavidGrey Thanks for this submission!
The idea here is for the method to be compatible with user input - which would be a String. We've updated the tests to be consistent about that.
